(function(){var z={"stroke-linejoin":"joinstyle",joinstyle:"joinstyle",endcap:"endcap",miterlimit:"miterlimit"},w=null;if(document.createStyleSheet&&document.namespaces){for(var x=".jsplumb_vml jsplumb\\:textbox jsplumb\\:oval jsplumb\\:rect jsplumb\\:stroke jsplumb\\:shape jsplumb\\:group".split(" "),w=document.createStyleSheet(),n=0;n<x.length;n++)w.addRule(x[n],"behavior:url(#default#VML);position:absolute;");document.namespaces.add("jsplumb","urn:schemas-microsoft-com:vml")}jsPlumb.vml={};var p=
function(a,b){for(var c in b)a[c]=b[c]},l=function(a,b,c,f,g,e){c=c||{};a=document.createElement("jsplumb:"+a);e?g.appendElement(a,f):jsPlumb.CurrentLibrary.appendElement(a,f);a.className=(c["class"]?c["class"]+" ":"")+"jsplumb_vml";q(a,b);p(a,c);return a},q=function(a,b,c){a.style.left=b[0]+"px";a.style.top=b[1]+"px";a.style.width=b[2]+"px";a.style.height=b[3]+"px";a.style.position="absolute";c&&(a.style.zIndex=c)},d=jsPlumb.vml.convertValue=function(a){return Math.floor(1E3*a)},s=function(a,b,c,
f){var g={};if(b.strokeStyle){g.stroked="true";var e=jsPlumbUtil.convertStyle(b.strokeStyle,!0);g.strokecolor=e;"transparent"===e?c.setOpacity("stroke","0.0"):c.setOpacity("stroke","1.0");g.strokeweight=b.lineWidth+"px"}else g.stroked="false";b.fillStyle?(g.filled="true",e=jsPlumbUtil.convertStyle(b.fillStyle,!0),g.fillcolor=e,"transparent"===e?c.setOpacity("fill","0.0"):c.setOpacity("fill","1.0")):g.filled="false";if(b.dashstyle)null==c.strokeNode?c.strokeNode=l("stroke",[0,0,0,0],{dashstyle:b.dashstyle},
a,f):c.strokeNode.dashstyle=b.dashstyle;else if(b["stroke-dasharray"]&&b.lineWidth){for(var e=-1==b["stroke-dasharray"].indexOf(",")?" ":",",d=b["stroke-dasharray"].split(e),h="",k=0;k<d.length;k++)h+=Math.floor(d[k]/b.lineWidth)+e;null==c.strokeNode?c.strokeNode=l("stroke",[0,0,0,0],{dashstyle:h},a,f):c.strokeNode.dashstyle=h}p(a,g)},t=function(){var a=this;jsPlumb.jsPlumbUIComponent.apply(this,arguments);this.opacityNodes={stroke:null,fill:null};this.initOpacityNodes=function(b){a.opacityNodes.stroke=
l("stroke",[0,0,1,1],{opacity:"0.0"},b,a._jsPlumb);a.opacityNodes.fill=l("fill",[0,0,1,1],{opacity:"0.0"},b,a._jsPlumb)};this.setOpacity=function(b,f){var g=a.opacityNodes[b];g&&(g.opacity=""+f)};var b=[];this.getDisplayElements=function(){return b};this.appendDisplayElement=function(c,f){f||a.canvas.parentNode.appendChild(c);b.push(c)}},u=jsPlumb.VmlConnector=function(a){var b=this;b.strokeNode=null;b.canvas=null;t.apply(this,arguments);var c=b._jsPlumb.connectorClass+(a.cssClass?" "+a.cssClass:
"");this.paint=function(f,g,e){if(null!=g){e={path:b.getPath(f)};if(g.outlineColor){var d=g.lineWidth+2*(g.outlineWidth||1),d={strokeStyle:jsPlumbUtil.convertStyle(g.outlineColor),lineWidth:d},h;for(h in z)d[h]=g[h];null==b.bgCanvas?(e["class"]=c,e.coordsize=1E3*f[2]+","+1E3*f[3],b.bgCanvas=l("shape",f,e,a.parent,b._jsPlumb,!0),q(b.bgCanvas,f,b.getZIndex()),b.appendDisplayElement(b.bgCanvas,!0),b.attachListeners(b.bgCanvas,b),b.initOpacityNodes(b.bgCanvas,["stroke"])):(e.coordsize=1E3*f[2]+","+1E3*
f[3],q(b.bgCanvas,f,b.getZIndex()),p(b.bgCanvas,e));s(b.bgCanvas,d,b)}null==b.canvas?(e["class"]=c,e.coordsize=1E3*f[2]+","+1E3*f[3],b.tooltip&&(e.label=b.tooltip),b.canvas=l("shape",f,e,a.parent,b._jsPlumb,!0),b.appendDisplayElement(b.canvas,!0),b.attachListeners(b.canvas,b),b.initOpacityNodes(b.canvas,["stroke"])):(e.coordsize=1E3*f[2]+","+1E3*f[3],q(b.canvas,f,b.getZIndex()),p(b.canvas,e));s(b.canvas,g,b,b._jsPlumb)}};this.reattachListeners=function(){b.canvas&&b.reattachListenersForElement(b.canvas,
b)}},y=window.VmlEndpoint=function(a){t.apply(this,arguments);var b=null,c=this;c.canvas=document.createElement("div");c.canvas.style.position="absolute";var f=c._jsPlumb.endpointClass+(a.cssClass?" "+a.cssClass:"");a._jsPlumb.appendElement(c.canvas,a.parent);c.tooltip&&c.canvas.setAttribute("label",c.tooltip);this.paint=function(a,e,d){var h={};jsPlumb.sizeCanvas(c.canvas,a[0],a[1],a[2],a[3]);null==b?(h["class"]=f,b=c.getVml([0,0,a[2],a[3]],h,d,c.canvas,c._jsPlumb),c.attachListeners(b,c),c.appendDisplayElement(b,
!0),c.appendDisplayElement(c.canvas,!0),c.initOpacityNodes(b,["fill"])):(q(b,[0,0,a[2],a[3]]),p(b,h));s(b,e,c)};this.reattachListeners=function(){b&&c.reattachListenersForElement(b,c)}};jsPlumb.Connectors.vml.Bezier=function(){jsPlumb.Connectors.Bezier.apply(this,arguments);u.apply(this,arguments);this.getPath=function(a){return"m"+d(a[4])+","+d(a[5])+" c"+d(a[8])+","+d(a[9])+","+d(a[10])+","+d(a[11])+","+d(a[6])+","+d(a[7])+" e"}};jsPlumb.Connectors.vml.Straight=function(){jsPlumb.Connectors.Straight.apply(this,
arguments);u.apply(this,arguments);this.getPath=function(a){return"m"+d(a[4])+","+d(a[5])+" l"+d(a[6])+","+d(a[7])+" e"}};jsPlumb.Connectors.vml.Flowchart=function(){jsPlumb.Connectors.Flowchart.apply(this,arguments);u.apply(this,arguments);this.getPath=function(a){for(var b="m "+d(a[4])+","+d(a[5])+" l",c=0;c<a[8];c++)b=b+" "+d(a[9+2*c])+","+d(a[10+2*c]);return b=b+" "+d(a[6])+","+d(a[7])+" e"}};jsPlumb.Endpoints.vml.Dot=function(){jsPlumb.Endpoints.Dot.apply(this,arguments);y.apply(this,arguments);
this.getVml=function(a,b,c,d,g){return l("oval",a,b,d,g)}};jsPlumb.Endpoints.vml.Rectangle=function(){jsPlumb.Endpoints.Rectangle.apply(this,arguments);y.apply(this,arguments);this.getVml=function(a,b,c,d,g){return l("rect",a,b,d,g)}};jsPlumb.Endpoints.vml.Image=jsPlumb.Endpoints.Image;jsPlumb.Endpoints.vml.Blank=jsPlumb.Endpoints.Blank;jsPlumb.Overlays.vml.Label=jsPlumb.Overlays.Label;jsPlumb.Overlays.vml.Custom=jsPlumb.Overlays.Custom;var v=function(a,b){a.apply(this,b);t.apply(this,b);var c=this;
c.canvas=null;c.isAppendedAtTopLevel=!0;this.paint=function(b,a,e,r,h,k){var m={};r&&(m.stroked="true",m.strokecolor=jsPlumbUtil.convertStyle(r,!0));e&&(m.strokeweight=e+"px");h&&(m.filled="true",m.fillcolor=h);e=Math.min(a.hxy.x,a.tail[0].x,a.tail[1].x,a.cxy.x);r=Math.min(a.hxy.y,a.tail[0].y,a.tail[1].y,a.cxy.y);var n=Math.max(a.hxy.x,a.tail[0].x,a.tail[1].x,a.cxy.x);h=Math.max(a.hxy.y,a.tail[0].y,a.tail[1].y,a.cxy.y);n=Math.abs(n-e);h=Math.abs(h-r);e=[e,r,n,h];a="m "+d(a.hxy.x)+","+d(a.hxy.y)+" l "+
d(a.tail[0].x)+","+d(a.tail[0].y)+" "+d(a.cxy.x)+","+d(a.cxy.y)+" "+d(a.tail[1].x)+","+d(a.tail[1].y)+" x e";m.path=a;m.coordsize=1E3*k[2]+","+1E3*k[3];e[0]=k[0];e[1]=k[1];e[2]=k[2];e[3]=k[3];null==c.canvas?(c.canvas=l("shape",e,m,b.canvas.parentNode,b._jsPlumb,!0),b.appendDisplayElement(c.canvas,!0),c.attachListeners(c.canvas,b),c.attachListeners(c.canvas,c)):(q(c.canvas,e),p(c.canvas,m))};this.reattachListeners=function(){c.canvas&&c.reattachListenersForElement(c.canvas,c)};this.cleanup=function(){null!=
c.canvas&&jsPlumb.CurrentLibrary.removeElement(c.canvas)}};jsPlumb.Overlays.vml.Arrow=function(){v.apply(this,[jsPlumb.Overlays.Arrow,arguments])};jsPlumb.Overlays.vml.PlainArrow=function(){v.apply(this,[jsPlumb.Overlays.PlainArrow,arguments])};jsPlumb.Overlays.vml.Diamond=function(){v.apply(this,[jsPlumb.Overlays.Diamond,arguments])}})();
