(function(){var q=function(b){return jsPlumb.CurrentLibrary.getOffset(jsPlumb.CurrentLibrary.getElementObject(b))},t=function(){var b=this;b.overlayPlacements=[];jsPlumb.jsPlumbUIComponent.apply(this,arguments);jsPlumbUtil.EventGenerator.apply(this,arguments);this._over=function(d){var a=q(jsPlumb.CurrentLibrary.getElementObject(b.canvas)),c=jsPlumb.CurrentLibrary.getPageXY(d);d=c[0]-a.left;a=c[1]-a.top;if(0<d&&0<a&&d<b.canvas.width&&a<b.canvas.height){for(c=0;c<b.overlayPlacements.length;c++){var f=
b.overlayPlacements[c];if(f&&f[0]<=d&&f[1]>=d&&f[2]<=a&&f[3]>=a)return!0}d=b.canvas.getContext("2d").getImageData(parseInt(d),parseInt(a),1,1);return 0!=d.data[0]||0!=d.data[1]||0!=d.data[2]||0!=d.data[3]}return!1};var c=!1,a=!1,f=!1;this.mousemove=function(a){jsPlumb.CurrentLibrary.getPageXY(a);var f=jsPlumb.CurrentLibrary.getClientXY(a),e=document.elementFromPoint(f[0],f[1]),f=null!=e&&jsPlumb.CurrentLibrary.hasClass(jsPlumb.CurrentLibrary.getElementObject(e),"_jsPlumb_overlay"),e=null!=e&&jsPlumb.CurrentLibrary.hasClass(jsPlumb.CurrentLibrary.getElementObject(e),
"_jsPlumb_endpoint")||null!=e&&jsPlumb.CurrentLibrary.hasClass(jsPlumb.CurrentLibrary.getElementObject(e),"_jsPlumb_connector");if(!c&&e&&b._over(a))return c=!0,b.fire("mouseenter",b,a),!0;!c||b._over(a)&&e||f||(c=!1,b.fire("mouseexit",b,a));b.fire("mousemove",b,a)};this.click=function(a){c&&b._over(a)&&!f&&b.fire("click",b,a);f=!1};this.dblclick=function(a){c&&b._over(a)&&!f&&b.fire("dblclick",b,a);f=!1};this.mousedown=function(d){b._over(d)&&!a&&(a=!0,q(jsPlumb.CurrentLibrary.getElementObject(b.canvas)),
b.fire("mousedown",b,d))};this.mouseup=function(d){a=!1;b.fire("mouseup",b,d)};this.contextmenu=function(a){c&&b._over(a)&&!f&&b.fire("contextmenu",b,a);f=!1}},r=function(b){var c=document.createElement("canvas");b._jsPlumb.appendElement(c,b.parent);c.style.position="absolute";b["class"]&&(c.className=b["class"]);b._jsPlumb.getId(c,b.uuid);b.tooltip&&c.setAttribute("title",b.tooltip);return c},s=function(b){t.apply(this,arguments);var c=[];this.getDisplayElements=function(){return c};this.appendDisplayElement=
function(a){c.push(a)}},m=jsPlumb.CanvasConnector=function(b){s.apply(this,arguments);var c=function(f,c){a.ctx.save();jsPlumb.extend(a.ctx,c);if(c.gradient){for(var b=a.createGradient(f,a.ctx),e=0;e<c.gradient.stops.length;e++)b.addColorStop(c.gradient.stops[e][0],c.gradient.stops[e][1]);a.ctx.strokeStyle=b}a._paint(f,c);a.ctx.restore()},a=this;a.canvas=r({"class":a._jsPlumb.connectorClass+" "+(b.cssClass||""),_jsPlumb:a._jsPlumb,parent:b.parent,tooltip:b.tooltip});a.ctx=a.canvas.getContext("2d");
a.appendDisplayElement(a.canvas);a.paint=function(f,b){null!=b&&(jsPlumb.sizeCanvas(a.canvas,f[0],f[1],f[2],f[3]),a.getZIndex()&&(a.canvas.style.zIndex=a.getZIndex()),null!=b.outlineColor&&c(f,{strokeStyle:b.outlineColor,lineWidth:b.lineWidth+2*(b.outlineWidth||1)}),c(f,b))}},n=function(b){var c=this;s.apply(this,arguments);c.canvas=r({"class":c._jsPlumb.endpointClass+" "+(b.cssClass||""),_jsPlumb:c._jsPlumb,parent:b.parent,tooltip:c.tooltip});c.ctx=c.canvas.getContext("2d");c.appendDisplayElement(c.canvas);
this.paint=function(a,b,d){jsPlumb.sizeCanvas(c.canvas,a[0],a[1],a[2],a[3]);c._paint.apply(this,arguments)}};jsPlumb.Endpoints.canvas.Dot=function(b){jsPlumb.Endpoints.Dot.apply(this,arguments);n.apply(this,arguments);var c=this,a=function(a){try{return parseInt(a)}catch(c){if("%"==a.substring(a.length-1))return parseInt(a.substring(0,a-1))}};this._paint=function(b,d,g){if(null!=d){var e=c.canvas.getContext("2d");g=g.getOrientation(c);jsPlumb.extend(e,d);if(d.gradient){var h;h=d.gradient;var k=c.defaultOffset,
l=c.defaultInnerRadius;h.offset&&(k=a(h.offset));h.innerRadius&&(l=a(h.innerRadius));h=[k,l];g=e.createRadialGradient(b[4],b[4],b[4],b[4]+(1==g[0]?-1*h[0]:h[0]),b[4]+(1==g[1]?-1*h[0]:h[0]),h[1]);for(h=0;h<d.gradient.stops.length;h++)g.addColorStop(d.gradient.stops[h][0],d.gradient.stops[h][1]);e.fillStyle=g}e.beginPath();e.arc(b[4],b[4],b[4],0,2*Math.PI,!0);e.closePath();(d.fillStyle||d.gradient)&&e.fill();d.strokeStyle&&e.stroke()}}};jsPlumb.Endpoints.canvas.Rectangle=function(b){var c=this;jsPlumb.Endpoints.Rectangle.apply(this,
arguments);n.apply(this,arguments);this._paint=function(a,b,d){var g=c.canvas.getContext("2d");d=d.getOrientation(c);jsPlumb.extend(g,b);if(b.gradient){d=g.createLinearGradient(1==d[0]?a[2]:0==d[0]?a[2]/2:0,1==d[1]?a[3]:0==d[1]?a[3]/2:0,-1==d[0]?a[2]:0==d[0]?a[2]/2:0,-1==d[1]?a[3]:0==d[1]?a[3]/2:0);for(var e=0;e<b.gradient.stops.length;e++)d.addColorStop(b.gradient.stops[e][0],b.gradient.stops[e][1]);g.fillStyle=d}g.beginPath();g.rect(0,0,a[2],a[3]);g.closePath();(b.fillStyle||b.gradient)&&g.fill();
b.strokeStyle&&g.stroke()}};jsPlumb.Endpoints.canvas.Triangle=function(b){var c=this;jsPlumb.Endpoints.Triangle.apply(this,arguments);n.apply(this,arguments);this._paint=function(a,b,d){var g=a[2];a=a[3];var e=c.canvas.getContext("2d"),h=0,k=0,l=0;d=d.getOrientation(c);1==d[0]&&(h=g,k=a,l=180);-1==d[1]&&(h=g,l=90);1==d[1]&&(k=a,l=-90);e.fillStyle=b.fillStyle;e.translate(h,k);e.rotate(l*Math.PI/180);e.beginPath();e.moveTo(0,0);e.lineTo(g/2,a/2);e.lineTo(0,a);e.closePath();(b.fillStyle||b.gradient)&&
e.fill();b.strokeStyle&&e.stroke()}};jsPlumb.Endpoints.canvas.Image=jsPlumb.Endpoints.Image;jsPlumb.Endpoints.canvas.Blank=jsPlumb.Endpoints.Blank;jsPlumb.Connectors.canvas.Bezier=function(){var b=this;jsPlumb.Connectors.Bezier.apply(this,arguments);m.apply(this,arguments);this._paint=function(c,a){b.ctx.beginPath();b.ctx.moveTo(c[4],c[5]);b.ctx.bezierCurveTo(c[8],c[9],c[10],c[11],c[6],c[7]);b.ctx.stroke()};this.createGradient=function(c,a,f){return b.ctx.createLinearGradient(c[6],c[7],c[4],c[5])}};
jsPlumb.Connectors.canvas.Straight=function(){var b=this,c=[null,[1,-1],[1,1],[-1,1],[-1,-1]];jsPlumb.Connectors.Straight.apply(this,arguments);m.apply(this,arguments);this._paint=function(a,f){b.ctx.beginPath();if(f.dashstyle&&2==f.dashstyle.split(" ").length){var d=f.dashstyle.split(" ");2!=d.length&&(d=[2,2]);for(var d=[d[0]*f.lineWidth,d[1]*f.lineWidth],g=(a[6]-a[4])/(a[7]-a[5]),e=jsPlumbUtil.segment([a[4],a[5]],[a[6],a[7]]),e=c[e],g=Math.atan(g),h=Math.sqrt(Math.pow(a[6]-a[4],2)+Math.pow(a[7]-
a[5],2)),h=Math.floor(h/(d[0]+d[1])),k=[a[4],a[5]],l=0;l<h;l++){b.ctx.moveTo(k[0],k[1]);var m=k[0]+Math.abs(Math.sin(g)*d[0])*e[0],n=k[1]+Math.abs(Math.cos(g)*d[0])*e[1],p=k[0]+Math.abs(Math.sin(g)*(d[0]+d[1]))*e[0],k=k[1]+Math.abs(Math.cos(g)*(d[0]+d[1]))*e[1];b.ctx.lineTo(m,n);k=[p,k]}b.ctx.moveTo(k[0],k[1])}else b.ctx.moveTo(a[4],a[5]);b.ctx.lineTo(a[6],a[7]);b.ctx.stroke()};this.createGradient=function(a,b){return b.createLinearGradient(a[4],a[5],a[6],a[7])}};jsPlumb.Connectors.canvas.Flowchart=
function(){var b=this;jsPlumb.Connectors.Flowchart.apply(this,arguments);m.apply(this,arguments);this._paint=function(c,a){b.ctx.beginPath();b.ctx.moveTo(c[4],c[5]);for(var f=0;f<c[8];f++)b.ctx.lineTo(c[9+2*f],c[10+2*f]);b.ctx.lineTo(c[6],c[7]);b.ctx.stroke()};this.createGradient=function(b,a){return a.createLinearGradient(b[4],b[5],b[6],b[7])}};jsPlumb.Overlays.canvas.Label=jsPlumb.Overlays.Label;jsPlumb.Overlays.canvas.Custom=jsPlumb.Overlays.Custom;var u=function(){jsPlumb.jsPlumbUIComponent.apply(this,
arguments)},p=function(b,c){b.apply(this,c);u.apply(this,c);this.paint=function(a,b,c,g,e){a=a.ctx;a.lineWidth=c;a.beginPath();a.moveTo(b.hxy.x,b.hxy.y);a.lineTo(b.tail[0].x,b.tail[0].y);a.lineTo(b.cxy.x,b.cxy.y);a.lineTo(b.tail[1].x,b.tail[1].y);a.lineTo(b.hxy.x,b.hxy.y);a.closePath();g&&(a.strokeStyle=g,a.stroke());e&&(a.fillStyle=e,a.fill())}};jsPlumb.Overlays.canvas.Arrow=function(){p.apply(this,[jsPlumb.Overlays.Arrow,arguments])};jsPlumb.Overlays.canvas.PlainArrow=function(){p.apply(this,[jsPlumb.Overlays.PlainArrow,
arguments])};jsPlumb.Overlays.canvas.Diamond=function(){p.apply(this,[jsPlumb.Overlays.Diamond,arguments])}})();
