(function(){jsPlumb.DOMElementComponent=function(a){jsPlumb.jsPlumbUIComponent.apply(this,arguments);this.mousemove=this.dblclick=this.click=this.mousedown=this.mouseup=function(b){}};jsPlumb.Connectors.Straight=function(){this.type="Straight";var a=this,b=null,e,c,d,k,f,m,g,h,p;this.compute=function(a,n,t,u,H,l,x,V){t=Math.abs(a[0]-n[0]);u=Math.abs(a[1]-n[1]);H=0.45*t;l=0.45*u;t*=1.9;u*=1.9;var K=Math.min(a[0],n[0])-H,F=Math.min(a[1],n[1])-l;x=Math.max(2*x,V);t<x&&(t=x,K=a[0]+(n[0]-a[0])/2-x/2,H=
(t-Math.abs(a[0]-n[0]))/2);u<x&&(u=x,F=a[1]+(n[1]-a[1])/2-x/2,l=(u-Math.abs(a[1]-n[1]))/2);f=a[0]<n[0]?H:t-H;m=a[1]<n[1]?l:u-l;g=a[0]<n[0]?t-H:H;h=a[1]<n[1]?u-l:l;b=[K,F,t,u,f,m,g,h];d=g-f;k=h-m;e=jsPlumbUtil.gradient({x:f,y:m},{x:g,y:h});c=-1/e;Math.atan(e);Math.atan(c);p=Math.sqrt(d*d+k*k);return b};this.pointOnPath=function(b,a){return 0!=b||a?1!=b||a?jsPlumbUtil.pointOnLine({x:f,y:m},{x:g,y:h},a?0<b?b:p+b:b*p):{x:g,y:h}:{x:f,y:m}};this.gradientAtPoint=function(b){return e};this.pointAlongPathFrom=
function(b,c,d){d=a.pointOnPath(b,d);return jsPlumbUtil.pointOnLine(d,1==b?{x:f+10*(g-f),y:m+10*(m-h)}:{x:g,y:h},c)}};jsPlumb.Connectors.Bezier=function(a){var b=this;a=a||{};this.majorAnchor=a.curviness||150;this.minorAnchor=10;var e=null;this.type="Bezier";this._findControlPoint=function(a,c,d,g,e,f,r){g=f.getOrientation(g);e=r.getOrientation(e);r=[];f=b.majorAnchor;var y=b.minorAnchor;g[0]==e[0]&&g[1]!=e[1]?(0==g[0]?r.push(c[0]<d[0]?a[0]+y:a[0]-y):r.push(a[0]-f*g[0]),0==g[1]?r.push(c[1]<d[1]?a[1]+
y:a[1]-y):r.push(a[1]+f*e[1])):(0==e[0]?r.push(d[0]<c[0]?a[0]+y:a[0]-y):r.push(a[0]+f*e[0]),0==e[1]?r.push(d[1]<c[1]?a[1]+y:a[1]-y):r.push(a[1]+f*g[1]));return r};var c,d,k,f,m,g,h,p,w,n;this.compute=function(a,l,x,t,u,F,r,y){r=r||0;w=Math.abs(a[0]-l[0])+r;n=Math.abs(a[1]-l[1])+r;h=Math.min(a[0],l[0])-r/2;p=Math.min(a[1],l[1])-r/2;k=a[0]<l[0]?w-r/2:r/2;g=a[1]<l[1]?n-r/2:r/2;f=a[0]<l[0]?r/2:w-r/2;m=a[1]<l[1]?r/2:n-r/2;c=b._findControlPoint([k,g],a,l,x,t,u,F);d=b._findControlPoint([f,m],l,a,t,x,F,u);
a=Math.min(k,f);l=Math.min(c[0],d[0]);a=Math.min(a,l);l=Math.max(k,f);x=Math.max(c[0],d[0]);l=Math.max(l,x);l>w&&(w=l);0>a&&(h+=a,a=Math.abs(a),w+=a,c[0]+=a,k+=a,f+=a,d[0]+=a);a=Math.min(g,m);l=Math.min(c[1],d[1]);a=Math.min(a,l);l=Math.max(g,m);x=Math.max(c[1],d[1]);l=Math.max(l,x);l>n&&(n=l);0>a&&(p+=a,a=Math.abs(a),n+=a,c[1]+=a,g+=a,m+=a,d[1]+=a);y&&w<y&&(a=(y-w)/2,w=y,h-=a,k+=a,f+=a,c[0]+=a,d[0]+=a);y&&n<y&&(a=(y-n)/2,n=y,p-=a,g+=a,m+=a,c[1]+=a,d[1]+=a);return e=[h,p,w,n,k,g,f,m,c[0],c[1],d[0],
d[1]]};var t=function(){return[{x:k,y:g},{x:c[0],y:c[1]},{x:d[0],y:d[1]},{x:f,y:m}]},u=function(a,b,c){c&&(b=jsBezier.locationAlongCurveFrom(a,0<b?0:1,b));return b};this.pointOnPath=function(a,b){var c=t();a=u(c,a,b);return jsBezier.pointOnCurve(c,a)};this.gradientAtPoint=function(a,b){var c=t();a=u(c,a,b);return jsBezier.gradientAtPoint(c,a)};this.pointAlongPathFrom=function(a,b,c){var d=t();a=u(d,a,c);return jsBezier.pointAlongCurveFrom(d,a,b)}};jsPlumb.Connectors.Flowchart=function(a){this.type=
"Flowchart";a=a||{};var b=this,e=a.stub||a.minStubLength||30,c=jsPlumbUtil.isArray(e)?e[0]:e,d=jsPlumbUtil.isArray(e)?e[1]:e,k=a.gap||0,f=[],m=0,g=[],h=[],p=[],w,n,t=-Infinity,u=-Infinity,H=Infinity,l=Infinity,x=function(a,b,c,d){for(b=a=0;b<f.length;b++)h[b]=f[b][5]/m,g[b]=[a,a+=f[b][5]/m]},V=function(){p.push(f.length);for(var a=0;a<f.length;a++)p.push(f[a][0]),p.push(f[a][1])},K=function(a,b,c,d,g,e){c=0==f.length?c:f[f.length-1][0];d=0==f.length?d:f[f.length-1][1];g=a==c?Infinity:0;e=Math.abs(a==
c?b-d:a-c);f.push([a,b,c,d,g,e]);m+=e;t=Math.max(t,a);u=Math.max(u,b);H=Math.min(H,a);l=Math.min(l,b)},F=function(a,b){b&&(a=0<a?a/m:(m+a)/m);for(var c=g.length-1,d=1,e=0;e<g.length;e++)if(g[e][1]>=a){c=e;d=(a-g[e][0])/h[e];break}return{segment:f[c],proportion:d,index:c}};this.compute=function(a,b,e,F,P,Q,W,v,O,L){f=[];g=[];m=0;h=[];t=u=-Infinity;H=l=Infinity;w=b[0]<a[0];n=b[1]<a[1];v=W||1;L=v/2+(c+d);var X=v/2+(d+c),R=v/2+(c+d),Y=v/2+(d+c);v=P.orientation||P.getOrientation(e);var q=Q.orientation||
Q.getOrientation(F);Q=w?b[0]:a[0];var U=n?b[1]:a[1],S=Math.abs(b[0]-a[0])+L+X,T=Math.abs(b[1]-a[1])+R+Y;if(0==v[0]&&0==v[1]||0==q[0]&&0==q[1]){var M=S>T?0:1,$=[1,0][M];v=[];q=[];v[M]=a[M]>b[M]?-1:1;q[M]=a[M]>b[M]?1:-1;v[$]=0;q[$]=0}var B=w?S-X+k*v[0]:L+k*v[0],G=n?T-Y+k*v[1]:R+k*v[1],z=w?L+k*q[0]:S-X+k*q[0],D=n?R+k*q[1]:T-Y+k*q[1],A=B+v[0]*c,C=G+v[1]*c,E=z+q[0]*d,I=D+q[1]*d,Z=Math.abs(B-z)>c+d,aa=Math.abs(G-D)>c+d,N=A+(E-A)/2,J=C+(I-C)/2;a=v[0]*q[0]+v[1]*q[1];p=[Q-L,U-R,S,T,B,G,z,D];b=0==v[0]?"y":
"x";a=-1==a?"opposite":1==a?"orthogonal":"perpendicular";var s=jsPlumbUtil.segment([B,G],[z,D]);L={x:[null,4,3,2,1],y:[null,2,1,4,3]};-1==v["x"==b?0:1]&&(s=L[b][s]);K(A,C,B,G,z,D);if(v={oppositex:function(){if(e.elementId==F.elementId){var a=C+(1-P.y)*O.height+Math.max(c,d);return[[A,a],[E,a]]}return!Z||1!=s&&2!=s?[[A,J],[E,J]]:[[N,G],[N,D]]},orthogonalx:function(){return 1==s||2==s?[[E,C]]:[[A,I]]},perpendicularx:function(){var a=(D+G)/2;if(1==s&&1==q[1]||2==s&&-1==q[1])return Math.abs(z-B)>Math.max(c,
d)?[[E,C]]:[[A,C],[A,a],[E,a]];if(3==s&&-1==q[1]||4==s&&1==q[1])return[[A,a],[E,a]];if(3==s&&1==q[1]||4==s&&-1==q[1])return[[A,I]];if(1==s&&-1==q[1]||2==s&&1==q[1])return Math.abs(z-B)>Math.max(c,d)?[[N,C],[N,I]]:[[A,I]]},oppositey:function(){if(e.elementId==F.elementId){var a=A+(1-P.x)*O.width+Math.max(c,d);return[[a,C],[a,I]]}return!aa||2!=s&&3!=s?[[N,C],[N,I]]:[[B,J],[z,J]]},orthogonaly:function(){return 2==s||3==s?[[A,I]]:[[E,C]]},perpendiculary:function(){var a=(z+B)/2;if(2==s&&-1==q[0]||3==
s&&1==q[0])return Math.abs(z-B)>Math.max(c,d)?[[A,I]]:[[A,J],[E,J]];if(1==s&&-1==q[0]||4==s&&1==q[0])return a=(z+B)/2,[[a,C],[a,I]];if(1==s&&1==q[0]||4==s&&-1==q[0])return[[E,C]];if(2==s&&1==q[0]||3==s&&-1==q[0])return Math.abs(D-G)>Math.max(c,d)?[[A,J],[E,J]]:[[E,C]]}}[a+b]())for(a=0;a<v.length;a++)K(v[a][0],v[a][1],B,G,z,D);K(E,I,B,G,z,D);K(z,D,B,G,z,D);V();x(B,G,z,D);u>p[3]&&(p[3]=u+2*W);t>p[2]&&(p[2]=t+2*W);return p};this.pointOnPath=function(a,c){return b.pointAlongPathFrom(a,0,c)};this.gradientAtPoint=
function(a,b){return f[F(a,b).index][4]};this.pointAlongPathFrom=function(a,b,c){a=F(a,c);c=a.segment;var d=a.proportion,e=f[a.index][5],g=f[a.index][4];return{x:Infinity==g?c[2]:c[2]>c[0]?c[0]+(1-d)*e-b:c[2]+d*e+b,y:0==g?c[3]:c[3]>c[1]?c[1]+(1-d)*e-b:c[3]+d*e+b,segmentInfo:a}}};jsPlumb.Endpoints.Dot=function(a){this.type="Dot";var b=this;a=a||{};this.radius=a.radius||10;this.defaultOffset=0.5*this.radius;this.defaultInnerRadius=this.radius/3;this.compute=function(a,c,d,k){c=d.radius||b.radius;return[a[0]-
c,a[1]-c,2*c,2*c,c]}};jsPlumb.Endpoints.Rectangle=function(a){this.type="Rectangle";var b=this;a=a||{};this.width=a.width||20;this.height=a.height||20;this.compute=function(a,c,d,k){c=d.width||b.width;d=d.height||b.height;return[a[0]-c/2,a[1]-d/2,c,d]}};var O=function(a){jsPlumb.DOMElementComponent.apply(this,arguments);var b=[];this.getDisplayElements=function(){return b};this.appendDisplayElement=function(a){b.push(a)}};jsPlumb.Endpoints.Image=function(a){this.type="Image";O.apply(this,arguments);
var b=this,e=!1,c=!1,d=a.width,k=a.height,f=null,m=a.endpoint;this.img=new Image;b.ready=!1;this.img.onload=function(){b.ready=!0;d=d||b.img.width;k=k||b.img.height;f&&f(b)};m.setImage=function(a,c){f=c;b.img.src=a;null!=b.canvas&&b.canvas.setAttribute("src",a)};m.setImage(a.src||a.url,a.onload);this.compute=function(a,c,e,f){b.anchorPoint=a;return b.ready?[a[0]-d/2,a[1]-k/2,d,k]:[0,0,0,0]};b.canvas=document.createElement("img");e=!1;b.canvas.style.margin=0;b.canvas.style.padding=0;b.canvas.style.outline=
0;b.canvas.style.position="absolute";b.canvas.className=jsPlumb.endpointClass+(a.cssClass?" "+a.cssClass:"");d&&b.canvas.setAttribute("width",d);k&&b.canvas.setAttribute("height",k);jsPlumb.appendElement(b.canvas,a.parent);b.attachListeners(b.canvas,b);b.cleanup=function(){c=!0};this.paint=function(a,f,m){b.ready?c||(e||(b.canvas.setAttribute("src",b.img.src),b.appendDisplayElement(b.canvas),e=!0),jsPlumb.sizeCanvas(b.canvas,b.anchorPoint[0]-d/2,b.anchorPoint[1]-k/2,d,k)):window.setTimeout(function(){b.paint(a,
f,m)},200)}};jsPlumb.Endpoints.Blank=function(a){var b=this;this.type="Blank";O.apply(this,arguments);this.compute=function(a,b,d,k){return[a[0],a[1],10,0]};b.canvas=document.createElement("div");b.canvas.style.display="block";b.canvas.style.width="1px";b.canvas.style.height="1px";b.canvas.style.background="transparent";b.canvas.style.position="absolute";b.canvas.className=b._jsPlumb.endpointClass;jsPlumb.appendElement(b.canvas,a.parent);this.paint=function(a,c,d){jsPlumb.sizeCanvas(b.canvas,a[0],
a[1],a[2],a[3])}};jsPlumb.Endpoints.Triangle=function(a){this.type="Triangle";a=a||{};a.width=a.width||55;a.height=a.height||55;this.width=a.width;this.height=a.height;this.compute=function(a,e,c,d){e=c.width||self.width;c=c.height||self.height;return[a[0]-e/2,a[1]-c/2,e,c]}};var U=function(a){var b=!0,e=this;this.isAppendedAtTopLevel=!0;this.component=a.component;this.loc=null==a.location?0.5:a.location;this.endpointLoc=null==a.endpointLocation?[0.5,0.5]:a.endpointLocation;this.setVisible=function(a){b=
a;e.component.repaint()};this.isVisible=function(){return b};this.hide=function(){e.setVisible(!1)};this.show=function(){e.setVisible(!0)};this.incrementLocation=function(a){e.loc+=a;e.component.repaint()};this.setLocation=function(a){e.loc=a;e.component.repaint()};this.getLocation=function(){return e.loc}};jsPlumb.Overlays.Arrow=function(a){this.type="Arrow";U.apply(this,arguments);this.isAppendedAtTopLevel=!1;a=a||{};var b=this;this.length=a.length||20;this.width=a.width||20;this.id=a.id;var e=
0>(a.direction||1)?-1:1,c=a.paintStyle||{lineWidth:1},d=a.foldback||0.623;this.computeMaxSize=function(){return 1.5*b.width};this.cleanup=function(){};this.draw=function(a,f,m){var g,h,p;if(a.pointAlongPathFrom){jsPlumbUtil.isString(b.loc)||1<b.loc||0>b.loc?(h=parseInt(b.loc),g=a.pointAlongPathFrom(h,e*b.length/2,!0),h=a.pointOnPath(h,!0),p=jsPlumbUtil.pointOnLine(g,h,b.length)):1==b.loc?(g=a.pointOnPath(b.loc),h=a.pointAlongPathFrom(b.loc,-1),p=jsPlumbUtil.pointOnLine(g,h,b.length)):0==b.loc?(p=
a.pointOnPath(b.loc),h=a.pointAlongPathFrom(b.loc,1),g=jsPlumbUtil.pointOnLine(p,h,b.length)):(g=a.pointAlongPathFrom(b.loc,e*b.length/2),h=a.pointOnPath(b.loc),p=jsPlumbUtil.pointOnLine(g,h,b.length));h=jsPlumbUtil.perpendicularLineTo(g,p,b.width);p=jsPlumbUtil.pointOnLine(g,p,d*b.length);var w=Math.min(g.x,h[0].x,h[1].x),n=Math.max(g.x,h[0].x,h[1].x),t=Math.min(g.y,h[0].y,h[1].y),u=Math.max(g.y,h[0].y,h[1].y);b.paint(a,{hxy:g,tail:h,cxy:p},c.lineWidth||f.lineWidth,c.strokeStyle||f.strokeStyle,c.fillStyle||
f.strokeStyle,m);return[w,n,t,u]}return[0,0,0,0]}};jsPlumb.Overlays.PlainArrow=function(a){a=a||{};a=jsPlumb.extend(a,{foldback:1});jsPlumb.Overlays.Arrow.call(this,a);this.type="PlainArrow"};jsPlumb.Overlays.Diamond=function(a){a=a||{};a=jsPlumb.extend(a,{length:(a.length||40)/2,foldback:2});jsPlumb.Overlays.Arrow.call(this,a);this.type="Diamond"};var Z=function(a){jsPlumb.DOMElementComponent.apply(this,arguments);U.apply(this,arguments);var b=this,e=!1;a=a||{};this.id=a.id;var c;this.getElement=
function(){null==c&&(c=a.create(a.component),c=jsPlumb.CurrentLibrary.getDOMElement(c),c.style.position="absolute",c.className=a._jsPlumb.overlayClass+" "+(b.cssClass?b.cssClass:a.cssClass?a.cssClass:""),jsPlumb.appendElement(c,a.component.parent),a._jsPlumb.getId(c),b.attachListeners(c,b),b.canvas=c);return c};this.getDimensions=function(){return jsPlumb.CurrentLibrary.getSize(jsPlumb.CurrentLibrary.getElementObject(b.getElement()))};var d=null,k=function(a){null==d&&(d=b.getDimensions());return d};
this.clearCachedDimensions=function(){d=null};this.computeMaxSize=function(){var a=k();return Math.max(a[0],a[1])};var f=b.setVisible;b.setVisible=function(a){f(a);c.style.display=a?"block":"none"};this.cleanup=function(){null!=c&&jsPlumb.CurrentLibrary.removeElement(c)};this.paint=function(a,d,f){e||(b.getElement(),a.appendDisplayElement(c),b.attachListeners(c,a),e=!0);c.style.left=f[0]+d.minx+"px";c.style.top=f[1]+d.miny+"px"};this.draw=function(a,c,d){c=k();if(null!=c&&2==c.length){var e={x:0,
y:0};if(a.pointOnPath){var e=b.loc,f=!1;if(jsPlumbUtil.isString(b.loc)||0>b.loc||1<b.loc)e=parseInt(b.loc),f=!0;e=a.pointOnPath(e,f)}else e=b.loc.constructor==Array?b.loc:b.endpointLoc,e={x:e[0]*d[2],y:e[1]*d[3]};minx=e.x-c[0]/2;miny=e.y-c[1]/2;b.paint(a,{minx:minx,miny:miny,td:c,cxy:e},d);return[minx,minx+c[0],miny,miny+c[1]]}return[0,0,0,0]};this.reattachListeners=function(a){c&&b.reattachListenersForElement(c,b,a)}};jsPlumb.Overlays.Custom=function(a){this.type="Custom";Z.apply(this,arguments)};
jsPlumb.Overlays.Label=function(a){var b=this;this.labelStyle=a.labelStyle||jsPlumb.Defaults.LabelStyle;this.cssClass=null!=this.labelStyle?this.labelStyle.cssClass:null;a.create=function(){return document.createElement("div")};jsPlumb.Overlays.Custom.apply(this,arguments);this.type="Label";var e=a.label||"",b=this,c=null;this.setLabel=function(a){e=a;c=null;b.clearCachedDimensions();d();b.component.repaint()};var d=function(){if("function"==typeof e){var a=e(b);b.getElement().innerHTML=a.replace(/\r\n/g,
"<br/>")}else null==c&&(c=e,b.getElement().innerHTML=c.replace(/\r\n/g,"<br/>"))};this.getLabel=function(){return e};var k=this.getDimensions;this.getDimensions=function(){d();return k()}}})();
